version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - mynetwork

  server:
    build:
      context: ./server
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
    working_dir: /server
    networks:
      - mynetwork

  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
